### ISSUE TITLE
Dashboard 500 Error:  Unable to determine latest available

### ISSUE THREAD

**Issue by chamblissb** [concerto/concerto-weather#46]
Getting a 500 error on the dashboard.  After a few tries, the dashboard comes up, but I get this error.

![concerto](https://user-images.githubusercontent.com/37554424/37618684-f4fc5df6-2bae-11e8-8563-3b7d6573ba02.PNG)

Production.log file:

I, [2018-03-19T12:58:11.361171 #1307]  INFO -- : Started GET "/dashboard" for 192.168.95.73 at 2018-03-19 12:58:11 -0500
I, [2018-03-19T12:58:11.361840 #1307]  INFO -- : Processing by DashboardController#show as HTML
I, [2018-03-19T12:58:11.388989 #1307]  INFO -- : Downloading latest Concerto version information for the first time.
I, [2018-03-19T12:58:11.539295 #1307]  INFO -- : Completed 500 Internal Server Error in 177ms (ActiveRecord: 1.9ms)
F, [2018-03-19T12:58:11.544000 #1307] FATAL -- : 
NoMethodError (undefined method `tag_name' for #<String:0x0055b97cc4e2b8>):
  lib/version_check.rb:14:in `latest_version'
  app/controllers/dashboard_controller.rb:43:in `show'
  app/controllers/application_controller.rb:112:in `set_time_zone'

**Comment by chamblissb** [comment]
Sorry, wrong area...
